### ISSUE TITLE
GDSC Soongsil 전체 member 추가

### ISSUE THREAD

**Issue by suyeon96** [gdsc-ssu/2021GithubContest#15]
EOM

**Comment by gomjellie** [comment]
??!!

**Comment by gomjellie** [comment]
앗 저 이거 올라오는 딱 그순간에 멤버 추가해서 main에 넣었는데

**Comment by gomjellie** [comment]
근데 전체 멤버는 추가 안했어요 신청자만...

**Comment by suyeon96** [comment]
이제 이거 만들어놨는데 전체추가 하는거 어떨까요?
이따 회의때 이야기해보죠 ㅋㅋ

**Comment by gomjellie** [comment]
![611637ED-EF3C-4B3F-83CB-A5F79683BB5D-7805-000006B3159FA9F6_file](https://user-images.githubusercontent.com/13645032/135859119-433d582e-3e30-4c0f-a46d-55e8e6f15511.jpg)

**Comment by gomjellie** [comment]
아 저 CI/CD 이해가 안돼요 ㅋㅋㅋㅋ 왜 이렇게 동작하는건지 이해안되는게 많아요. 왜 코드가 최신버전으로 runner에서 안돌아가는지 모르겠네요 ㅋㅋㅋㅋ

**Comment by gomjellie** [comment]
회의결과 전체멤버 -> 신청멤버만 넣기로 결정
